<a href="https://colab.research.google.com/github/KendallScott/ML2/blob/main/Homework3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task
The problem is: you and your work friends are trying to decide where to go for lunch. You have to pick a restaurant that’s best for everyone.  Then you should decide if you should split into two groups so everyone is happier.  

Despite the simplicity of the process you will need to make decisions regarding how to process the data.
  
This process was thoroughly investigated in the operation research community.  This approach can prove helpful on any number of decision making problems that are currently not leveraging machine learning.  

You asked your 10 work friends to answer a survey. They gave you back the following dictionary object.  

people = {'Jane': {'willingness to travel':
                  'desire for new experience':
                  'cost':
                  'indian food':
                  'mexican food':
                  'hipster points':
                  'vegetarian': }
                }          

Questions
1. Transform the user data into a matrix ( M_people). Keep track of column and row IDs.   








In [243]:
import itertools
import numpy as np

people = {'Jane': {'willingness to travel':5, 'desire for new experience':8,'cost':9, 'indian food': 5,'mexican food': 7,'hipster points':8, 'vegetarian': 7},
          'Sam': {'willingness to travel':7, 'desire for new experience':9,'cost':8, 'indian food': 7,'mexican food': 8,'hipster points':7, 'vegetarian': 6},
          'John': {'willingness to travel':3, 'desire for new experience':5,'cost':7, 'indian food': 4,'mexican food': 9,'hipster points':5, 'vegetarian': 5},
          'Thomas': {'willingness to travel':4, 'desire for new experience':6,'cost':5, 'indian food': 3,'mexican food': 5,'hipster points':6, 'vegetarian': 4},
          'Harry': {'willingness to travel':5, 'desire for new experience':7,'cost':4, 'indian food': 5,'mexican food': 4,'hipster points':7, 'vegetarian': 6},
          'Sarah': {'willingness to travel':7, 'desire for new experience':5,'cost':3, 'indian food': 6,'mexican food': 3,'hipster points':5, 'vegetarian': 5},
          'Rebekka': {'willingness to travel':8, 'desire for new experience':4,'cost':5, 'indian food': 7,'mexican food': 3,'hipster points':4, 'vegetarian': 4},
          'Esi': {'willingness to travel':9, 'desire for new experience':6,'cost':6, 'indian food': 8,'mexican food': 9,'hipster points':3, 'vegetarian':3},
          'Berbel': {'willingness to travel':8, 'desire for new experience':8,'cost':7, 'indian food': 6,'mexican food': 9,'hipster points':2, 'vegetarian': 3},
          'Danna': {'willingness to travel':6, 'desire for new experience':9,'cost':8, 'indian food': 4,'mexican food': 9,'hipster points':1, 'vegetarian': 2}
          }

names = list(people.keys())
column_names = list(list(people.values())[0].keys())

# Create a matrix
M_people = np.zeros((len(names), len(column_names)))

for i, (name, column) in enumerate(itertools.product(names, column_names)):
    j =column_names.index(column)
    i =names.index(name)
    M_people[i][j] = people.get(name).get(column)

M_people

array([[5., 8., 9., 5., 7., 8., 7.],
       [7., 9., 8., 7., 8., 7., 6.],
       [3., 5., 7., 4., 9., 5., 5.],
       [4., 6., 5., 3., 5., 6., 4.],
       [5., 7., 4., 5., 4., 7., 6.],
       [7., 5., 3., 6., 3., 5., 5.],
       [8., 4., 5., 7., 3., 4., 4.],
       [9., 6., 6., 8., 9., 3., 3.],
       [8., 8., 7., 6., 9., 2., 3.],
       [6., 9., 8., 4., 9., 1., 2.]])

2.  Next you collected data from an internet website. You got the following information.

restaurants  = {'flacos':{'distance' :
                        'novelty' :
                        'cost':
                        'average rating':
                        'cuisine':
                        'vegetarian':}}

3. Transform the restaurant data into a matrix (M_resturants) using the same column index.



In [387]:
restaurants  = {'flacos':{'distance' : 8, 'novelty' : 9, 'cost': 3, 'indian food':0, 'mexican food':0,'hipster':10, 'vegetarian':3},
                'chipotles':{'distance' :10, 'novelty' : 4, 'cost': 9, 'indian food':0, 'mexican food':10,'hipster':10, 'vegetarian':9},
                'taco_hut':{'distance' :3, 'novelty' : 1, 'cost': 10, 'indian food':0, 'mexican food':10,'hipster':10, 'vegetarian':1},
                'chat_samosa':{'distance' :5, 'novelty' : 10, 'cost': 7, 'indian food':10, 'mexican food':0,'hipster':10, 'vegetarian':2},
                'chat_samosas':{'distance' :5, 'novelty' : 10, 'cost': 7, 'indian food':10, 'mexican food':0,'hipster':10, 'vegetarian':9},
                'chat_samosar':{'distance' :5, 'novelty' : 10, 'cost': 7, 'indian food':10, 'mexican food':0,'hipster':10, 'vegetarian':8},
                'chat_samosav':{'distance' :5, 'novelty' : 10, 'cost': 7, 'indian food':10, 'mexican food':0,'hipster':10, 'vegetarian':7},
                'chat_samosab':{'distance' :5, 'novelty' : 10, 'cost': 7, 'indian food':10, 'mexican food':0,'hipster':10, 'vegetarian':6},
                'chat_samosast':{'distance' :5, 'novelty' : 10, 'cost': 7, 'indian food':10, 'mexican food':0,'hipster':10, 'vegetarian':5},
                'chat_samosaa':{'distance' :5, 'novelty' : 10, 'cost': 7, 'indian food':10, 'mexican food':0,'hipster':10, 'vegetarian':3}
                }

restaurant_names = list(restaurants.keys())
column_names = list(list(restaurants.values())[0].keys())

# Create a matrix
M_restaurants = np.zeros((len(restaurant_names), len(column_names)))

for i, (name, column) in enumerate(itertools.product(restaurant_names, column_names)):
    j =column_names.index(column)
    i =restaurant_names.index(name)
    M_restaurants[i][j] = restaurants.get(name).get(column)

M_restaurants

array([[ 8.,  9.,  3.,  0.,  0., 10.,  3.],
       [10.,  4.,  9.,  0., 10., 10.,  9.],
       [ 3.,  1., 10.,  0., 10., 10.,  1.],
       [ 5., 10.,  7., 10.,  0., 10.,  2.],
       [ 5., 10.,  7., 10.,  0., 10.,  9.],
       [ 5., 10.,  7., 10.,  0., 10.,  8.],
       [ 5., 10.,  7., 10.,  0., 10.,  7.],
       [ 5., 10.,  7., 10.,  0., 10.,  6.],
       [ 5., 10.,  7., 10.,  0., 10.,  5.],
       [ 5., 10.,  7., 10.,  0., 10.,  3.]])

4. The most important idea in this project is the idea of a linear combination. Informally describe what a linear combination is  and how it will relate to our restaurant matrix.



5. Choose a person and compute (using a linear combination) the top restaurant for them.  What does each entry in the resulting vector represent?



In [286]:
Danna = M_people[name.index('Danna')]
Danna_restaurants =Danna*M_restaurants
Danna_restaurants

array([[40., 72., 27.,  0.,  0., 80., 21.],
       [50., 32., 81.,  0., 70., 80., 63.],
       [15.,  8., 90.,  0., 70., 80.,  7.],
       [25., 80., 63., 50.,  0., 80., 14.],
       [25., 80., 63., 50.,  0., 80., 63.],
       [25., 80., 63., 50.,  0., 80., 56.],
       [25., 80., 63., 50.,  0., 80., 49.],
       [25., 80., 63., 50.,  0., 80., 42.],
       [25., 80., 63., 50.,  0., 80., 35.],
       [25., 80., 63., 50.,  0., 80., 21.]])

In [364]:
Danna_M_restaurants = np.sum(Danna*M_restaurants, axis=1)
Danna_max = np.max(Danna_M_restaurants)
Danna_max

376.0

In [366]:
restaurant_list = (Danna_M_restaurants==Danna_max)

for idx, val in np.ndenumerate(restaurant_list):
        if val == True:
          idx_res = idx[0]

print('Dannas top pick is ', restaurant_names[idx_res], 'at score: ', Danna_max)

Dannas top pick is  chipotles at score:  376.0


6. Next, compute a new matrix (M_usr_x_rest  i.e. an user by restaurant) from all people.  What does the a_ij matrix represent?  Sum all columns in M_usr_x_rest to get the optimal restaurant for all users.  What do the entries represent?



In [417]:
M_usr_x_rest = np.zeros((len(names), len(restaurant_names)))

for i,name in enumerate(names):
  for j,restaurant in enumerate(restaurant_names):
    M_usr_x_rest[i,j] = (np.sum(M_people[i]*M_restaurants[j]))
M_usr_x_rest

array([[240., 376., 270., 312., 361., 354., 347., 340., 333., 319.],
       [249., 382., 266., 333., 375., 369., 363., 357., 351., 339.],
       [155., 298., 229., 214., 249., 244., 239., 234., 229., 219.],
       [173., 255., 182., 213., 241., 237., 233., 229., 225., 217.],
       [203., 278., 178., 255., 297., 291., 285., 279., 273., 261.],
       [175., 242., 141., 226., 261., 256., 251., 246., 241., 231.],
       [167., 247., 152., 233., 261., 257., 253., 249., 245., 237.],
       [183., 315., 216., 263., 284., 281., 278., 275., 272., 266.],
       [186., 312., 215., 255., 276., 273., 270., 267., 264., 258.],
       [169., 286., 209., 230., 244., 242., 240., 238., 236., 232.]])

In [487]:
np.insert(M_results, 0, 376)

array([376.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.])

In [490]:
M_usr_x_rest_max = np.max(M_usr_x_rest, axis=1)
# Create a matrix
M_results = np.zeros((len(names)))
scores = []

for x,i in enumerate(names):
  insert_val = np.hstack((names[x], M_usr_x_rest_max[x]))
  M_results[x] =  M_usr_x_rest_max[x]

M_results

array([376., 382., 298., 255., 297., 261., 261., 315., 312., 286.])

In [519]:
for i,idx, in enumerate(names):
  restaurant_list_results = M_usr_x_rest[i]==M_results.T[i]
  name_current = idx

  for idx, val in np.ndenumerate(restaurant_list_results):
          if val == True:
            idx_res = idx[0]

  print(name_current, ' top pick is ', restaurant_names[idx_res], 'at score: ', M_results[i])



Jane  top pick is  chipotles at score:  376.0
Sam  top pick is  chipotles at score:  382.0
John  top pick is  chipotles at score:  298.0
Thomas  top pick is  chipotles at score:  255.0
Harry  top pick is  chat_samosas at score:  297.0
Sarah  top pick is  chat_samosas at score:  261.0
Rebekka  top pick is  chat_samosas at score:  261.0
Esi  top pick is  chipotles at score:  315.0
Berbel  top pick is  chipotles at score:  312.0
Danna  top pick is  chipotles at score:  286.0


7. Now convert each row in the M_usr_x_rest into a ranking for each user and call it M_usr_x_rest_rank.   Do the same as above to generate the optimal restaurant choice.  



8. Why is there a difference between the two?  What problem arrives?  What does it represent in the real world?



9. How should you preprocess your data to remove this problem?



10. Find  user profiles that are problematic, explain why?



11. Think of two metrics to compute the disatistifaction with the group.  



12. Based on this dissatisfaction metric, should you split into two groups today?



13. Ok. Now you just found out the boss is paying for the meal. How should you adjust? Now what is the best restaurant?



14. Tomorrow you visit another team. You have the same restaurants and they told you their optimal ordering for restaurants. Can you find their weight matrix?